---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "nomad_metrics"
    consul_sd_configs:
      - server: "consul.service.consul:8500"
        services: ["nomad-client", "nomad"]
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: ["__meta_consul_tags"]
        regex: "(.*)http(.*)"
        action: keep
    metrics_path: /v1/metrics
    params:
      format: ["prometheus"]
